language: rust

addons:
  apt:
    packages:
      - build-essential
      - libfontconfig1
      - cmake
      - binutils-dev

rust:
  - nightly

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qtdeclarative5-dev 
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install:
  - travis-cargo fetch

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH"

script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench

after_success:
  - travis-cargo coveralls --no-sudo --verify

